CREATE DATABASE IF NOT EXISTS openpodcast;

CREATE TABLE IF NOT EXISTS podcastConnectWaitlist (
  env_name VARCHAR(64) NOT NULL,
  env_value VARCHAR(64) NOT NULL,
  value_encrypted BOOLEAN NOT NULL DEFAULT FALSE,
  session_id CHAR(36) NOT NULL,
  inserted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (session_id, env_name)
);